services:
  db:
    image: postgres:16
    container_name: garita_postgres
    restart: always
    environment:
      POSTGRES_DB: garita_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: garita_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: garita_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/static:/app/static
    depends_on:
      - db

  frontend:
    image: nginx:alpine
    container_name: garita_frontend
    restart: always
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  postgres_data:
